# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank='false', max_length=50)),
                ('phone_number', models.CharField(blank='false', max_length=20)),
                ('country', models.CharField(blank='false', max_length=20)),
                ('postcode', models.CharField(blank='true', max_length=10)),
                ('town_or_city', models.CharField(blank='false', max_length=50)),
                ('street_address1', models.CharField(blank='false', max_length=50)),
                ('street_address2', models.CharField(blank='false', max_length=50)),
                ('county', models.CharField(blank='false', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank='false')),
                ('order', models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('product', models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
