# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
